name: Build PJSIP for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Umożliwia ręczne uruchamianie workflow

jobs:
  build-pjsip:
    name: Build PJSIP
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Android NDK
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      # 3. Build PJSIP using ndk-build
      - name: Build PJSIP
        run: |
          export NDK_PROJECT_PATH=.
          export APP_BUILD_SCRIPT=./Android.mk
          export NDK_APPLICATION_MK=./Application.mk
          ndk-build

      # 4. Upload the compiled libraries as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pjsip-libs
          path: ./libs # Upewnij się, że wskazuje na katalog z bibliotekami wynikowymi
