name: Build PJSIP for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-pjsip:
    name: Build PJSIP for multiple Android architectures
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Android NDK
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c # Specify the NDK version (latest stable or preferred version)

      # Step 3: Add NDK to PATH
      - name: Add NDK to PATH
        run: |
          export ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64
          export PATH=$ANDROID_NDK_ROOT:$PATH
          echo "ANDROID_NDK_ROOT set to $ANDROID_NDK_ROOT"
          echo "Updated PATH: $PATH"

      # Step 4: Configure and Build PJSIP for arm64-v8a architecture
      - name: Configure and Build PJSIP for arm64-v8a
        run: |
          cd /home/runner/work/pjproject/pjproject
          TARGET_ABI=arm64-v8a ./configure-android --use-ndk-cflags
          make dep && make clean && make

      # Step 5: Configure and Build PJSIP for armeabi-v7a architecture
      - name: Configure and Build PJSIP for armeabi-v7a
        run: |
          cd /home/runner/work/pjproject/pjproject
          TARGET_ABI=armeabi-v7a ./configure-android --use-ndk-cflags
          make dep && make clean && make

      # Step 6: Configure and Build PJSIP for x86 architecture
      - name: Configure and Build PJSIP for x86
        run: |
          cd /home/runner/work/pjproject/pjproject
          TARGET_ABI=x86 ./configure-android --use-ndk-cflags
          make dep && make clean && make

      # Step 8: Print .so files directory
      - name: Find .so files
        run: |
          find $GITHUB_WORKSPACE -name "*.so"

      # Step 9: Upload compiled libraries as artifacts
      - name: Upload arm64-v8a libraries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pjsip-arm64-v8a-libs
          path: /home/runner/work/pjproject/pjproject/libs

      - name: Upload armeabi-v7a libraries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pjsip-armeabi-v7a-libs
          path: /home/runner/work/pjproject/pjproject/libs

      - name: Upload x86 libraries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pjsip-x86-libs
          path: /home/runner/work/pjproject/pjproject/libs
