name: Build PJSUA2 for Android (TLS Enabled)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Add NDK to PATH
        run: |
          echo "ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Install dependencies (SWIG, OpenSSL, Crypto++)
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake libtool pkg-config libssl-dev libcrypto++-dev

      - name: Set up environment variables with TLS support
        run: |
          echo "BASE_FOLDER=${{ github.workspace }}" >> $GITHUB_ENV
          CONFIG_SITE_PATH="${{ github.workspace }}/pjlib/include/pj/config_site.h"
          mkdir -p "$(dirname "$CONFIG_SITE_PATH")"
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #define PJMEDIA_HAS_G7221_CODEC 1
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSIP_SSL_USE_BUILTIN 1
          #include <pj/config_site_sample.h>
          EOF

      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

  build-android:
    name: Build for ${{ matrix.abi }}
    runs-on: ubuntu-latest
    needs: setup-environment
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86, x86_64]

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      - name: Build for ${{ matrix.abi }} with TLS
        run: |
          cd ${{ github.workspace }}
          TARGET_ABI=${{ matrix.abi }} ./configure-android --use-ndk-cflags --enable-tls
          make dep && make clean && make
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload ${{ matrix.abi }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-${{ matrix.abi }}
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/${{ matrix.abi }}

  upload-all-artifacts:
    name: Upload all compiled libraries
    runs-on: ubuntu-latest
    needs: build-android

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: pjsua2-all-architectures
          path: libpjsua2-*/
