name: Build PJSUA2 for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # 🔹 Step 1: Setup the Environment
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      # ✅ Set up Android NDK
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      # ✅ Add NDK to PATH
      - name: Add NDK to PATH
        run: |
          echo "ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      # ✅ Install SWIG and other dependencies
      - name: Install SWIG and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake libtool pkg-config

      # ✅ Download and extract OpenSSL
      - name: Download and extract OpenSSL
        run: |
          curl -L https://github.com/openssl/openssl/releases/download/openssl-3.4.0/openssl-3.4.0.tar.gz -o openssl.tar.gz
          tar -xvzf openssl.tar.gz

      # ✅ Set up environment variables for PJSUA2
      - name: Set up environment variables
        run: |
          echo "BASE_FOLDER=${{ github.workspace }}" >> $GITHUB_ENV
          CONFIG_SITE_PATH="${{ github.workspace }}/pjlib/include/pj/config_site.h"
          mkdir -p "$(dirname "$CONFIG_SITE_PATH")"
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #define PJMEDIA_HAS_G7221_CODEC 1
          #include <pj/config_site_sample.h>
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSUA_MAX_ACC 10     
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSIP_HAS_TLS 1
          #define PJ_HAS_SSL_SOCK 1
          EOF

  # 🔹 Step 2: Build PJSUA2 for Multiple Architectures
  build-architectures:
    name: Build for ${{ matrix.architecture }}
    runs-on: ubuntu-latest
    needs: setup-environment
    strategy:
      matrix:
        architecture: [arm64-v8a, armeabi-v7a, x86, x86_64]

    steps:
      # ✅ Restore the environment
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      # ✅ Grant execute permissions to scripts
      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      # ✅ Set up NDK toolchain for compilation
      - name: Set up toolchain paths
        run: |
          export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
          echo "TOOLCHAIN=$TOOLCHAIN" >> $GITHUB_ENV
          echo "$TOOLCHAIN/bin" >> $GITHUB_PATH
          
          echo "CC_aarch64=$TOOLCHAIN/bin/aarch64-linux-android23-clang" >> $GITHUB_ENV
          echo "CC_arm=$TOOLCHAIN/bin/armv7a-linux-androideabi23-clang" >> $GITHUB_ENV
          echo "CC_x86=$TOOLCHAIN/bin/i686-linux-android23-clang" >> $GITHUB_ENV
          echo "CC_x86_64=$TOOLCHAIN/bin/x86_64-linux-android23-clang" >> $GITHUB_ENV

      # ✅ Build OpenSSL for the selected architecture
      - name: Build OpenSSL for ${{ matrix.architecture }}
        run: |
          cd ${{ github.workspace }}/openssl-3.4.0
          
          case "${{ matrix.architecture }}" in
            arm64-v8a)
              export CC=$CC_aarch64
              ./Configure android-arm64 -D__ANDROID_API__=23 ;;
            armeabi-v7a)
              export CC=$CC_arm
              ./Configure android-arm -D__ANDROID_API__=23 ;;
            x86)
              export CC=$CC_x86
              ./Configure android-x86 -D__ANDROID_API__=23 ;;
            x86_64)
              export CC=$CC_x86_64
              ./Configure android-x86_64 -D__ANDROID_API__=23 ;;
          esac

          make -j$(nproc)

      # ✅ Build PJSUA2 for the selected architecture
      - name: Build PJSUA2 for ${{ matrix.architecture }}
        run: |
          export OPENSSL_DIR=${{ github.workspace }}/openssl-3.4.0
          TARGET_ABI=${{ matrix.architecture }}
          
          cd ${{ github.workspace }}
           TARGET_ABI=${{ matrix.architecture }} ./configure-android \
           --use-ndk-cflags \
           --with-ssl=$OPENSSL_DIR/include
           make dep && make clean && make

      # ✅ Build Java files (only for arm64-v8a)
      - name: Build Java files
        if: matrix.architecture == 'arm64-v8a'
        run: |
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      # ✅ Upload Java artifacts (SWIG-generated)
      - name: Upload Java artifact
        if: matrix.architecture == 'arm64-v8a'
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-java-swing-wrapper
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/

      # ✅ Upload compiled `.so` files for each architecture
      - name: Upload compiled libraries
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-${{ matrix.architecture }}
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/

  # 🔹 Step 3: Package Everything into `android-lib`
  package-android-lib:
    name: Package Final Android Library
    runs-on: ubuntu-latest
    needs: build-architectures

    steps:
      # ✅ Download all compiled artifacts
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      # ✅ Merge everything into `android-lib`
      - name: Create final android-lib directory
        run: |
          mkdir -p android-lib/pjsua2/src/main/jniLibs
          mkdir -p android-lib/pjsua2/src/main/java/org/pjsip

          # Move native libraries (.so) into jniLibs
          mv libpjsua2-*/* android-lib/pjsua2/src/main/jniLibs/

          # Move Java bindings (SWIG-generated) into src/main/java
          mv libpjsua2-java-swing-wrapper/* android-lib/

      # ✅ Upload final `android-lib` artifact
      - name: Upload final android-lib
        uses: actions/upload-artifact@v3
        with:
          name: android-lib
          path: android-lib
