name: Build PJSUA2 for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Add NDK to PATH
        run: |
          echo "ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Install SWIG and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake libtool pkg-config

      - name: Install OpenSSL for Android
        run: |
          # Download and extract OpenSSL
          curl -L https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1k.tar.gz -o openssl.tar.gz
          tar -xvzf openssl.tar.gz

          # Set up OpenSSL for different architectures
          for target in arm64-v8a armeabi-v7a x86 x86_64; do
            PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$ANDROID_NDK_ROOT/toolchains/$target/prebuilt/linux-x86_64/bin:$PATH
            ./Configure android-$target -D__ANDROID_API__=29

            # Build OpenSSL for Android
            make

            # Create lib directory and copy libraries
            mkdir -p lib
            cp lib*.a lib/
            ls lib/
          done

          export OPENSSL_DIR=${{ github.workspace }}/openssl-1.1.1k
          # Save OPENSSL_DIR as environment variable
          echo "OPENSSL_DIR=$PWD" >> $GITHUB_ENV

      - name: Set up environment variables
        run: |
          echo "BASE_FOLDER=${{ github.workspace }}" >> $GITHUB_ENV
          CONFIG_SITE_PATH="${{ github.workspace }}/pjlib/include/pj/config_site.h"
          mkdir -p "$(dirname "$CONFIG_SITE_PATH")"
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #define PJMEDIA_HAS_G7221_CODEC 1
          #include <pj/config_site_sample.h>
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSUA_MAX_CALLS 10     
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSIP_HAS_TLS 1
          #define PJ_HAS_SSL_SOCK 1
          EOF

      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

  build-architectures:
    name: Build for multiple architectures
    runs-on: ubuntu-latest
    needs: setup-environment
    strategy:
      matrix:
        architecture: [arm64-v8a, armeabi-v7a, x86, x86_64]
    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      - name: Build for ${{ matrix.architecture }}
        run: |
          cd ${{ github.workspace }}
          TARGET_ABI=${{ matrix.architecture }} ./configure-android --use-ndk-cflags --enable-tls
          make dep && make clean && make
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload ${{ matrix.architecture }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-${{ matrix.architecture }}
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/${{ matrix.architecture }}

  upload-all-artifacts:
    name: Upload all compiled libraries
    runs-on: ubuntu-latest
    needs: build-architectures

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: pjsua2-all-architectures
          path: libpjsua2-*/ 
