name: Build PJSIP for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-pjsip:
    name: Build PJSIP
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository (your forked branch)
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref_name }}

      # Set up Android SDK and NDKM
    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35       
        ndk: 27.2.12479018   
        target: default       
        channel: stable             

    # 3. Install dependencies
    - name: Install dependencies
      run: sudo apt-get install -y build-essential python3

    # 4. Build PJSIP for Android
    - name: Build PJSIP
      env:
        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        cd pjproject
        export ANDROID_NDK_ROOT=$ANDROID_NDK
        ./configure-android
        make dep && make
    # 5. Upload the compiled libraries as artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pjsip-libs
        path: pjproject/output/lib
