name: Build PJSIP for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-pjsip:
    name: Build PJSIP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Android NDK
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c # Specify the NDK version (latest stable or preferred version)

      # Step 3: Set up environment variables and build PJSIP using ndk-build
      - name: Build PJSIP
        run: |
          # Set up the Android NDK project path
          export NDK_PROJECT_PATH=$(pwd)
          
          # Ensure the Android.mk file exists in the correct directory
          export APP_BUILD_SCRIPT=$(pwd)/jni/Android.mk
          
          # Set the minimum platform version for Android
          export APP_PLATFORM=android-21

          # Run ndk-build to build PJSIP
          ndk-build

      # Step 4: Upload the compiled libraries as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pjsip-libs
          path: ./libs # Path to the output directory containing .so libraries
