name: Build PJSUA2 for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # Job: Setup environment once and reuse it
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Add NDK to PATH
        run: |
          echo "ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Install SWIG and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake libtool pkg-config

      - name: Set up environment variables
        run: |
          echo "BASE_FOLDER=${{ github.workspace }}" >> $GITHUB_ENV
          CONFIG_SITE_PATH="${{ github.workspace }}/pjlib/include/pj/config_site.h"
          mkdir -p "$(dirname "$CONFIG_SITE_PATH")"
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #define PJMEDIA_HAS_G7221_CODEC 1
          #include <pj/config_site_sample.h>
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1
          EOF

      - name: Save environment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pjsua2-environment
          path: ${{ github.workspace }}

  # Job: Build for arm64-v8a
  build-arm64-v8a:
    name: Build for arm64-v8a
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Download environment
        uses: actions/download-artifact@v4
        with:
          name: pjsua2-environment
          path: ${{ github.workspace }}

      - name: Build for arm64-v8a
        run: |
          cd ${{ github.workspace }}
          ./configure-android --use-ndk-cflags
          make dep && make clean && make

          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload arm64-v8a artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-arm64-v8a
          path: ${{ github.workspace }}/pjsip-apps
          
  # Job: Build for armeabi-v7a
  build-armeabi-v7a:
    name: Build for armeabi-v7a
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Download environment
        uses: actions/download-artifact@v4
        with:
          name: pjsua2-environment
          path: ${{ github.workspace }}

      - name: Build for armeabi-v7a
        run: |
          cd ${{ github.workspace }}
          ./configure-android --use-ndk-cflags
          make dep && make clean && make

          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload armeabi-v7a artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-armeabi-v7a
          path: ${{ github.workspace }}/pjsip-apps

  # Job: Build for x86
  build-x86:
    name: Build for x86
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Download environment
        uses: actions/download-artifact@v4
        with:
          name: pjsua2-environment
          path: ${{ github.workspace }}

      - name: Build for x86
        run: |
          cd ${{ github.workspace }}
          ./configure-android --use-ndk-cflags
          make dep && make clean && make

          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-x86
          path: ${{ github.workspace }}/pjsip-apps

  # Job: Collect all artifacts
  upload-all-artifacts:
    name: Upload all compiled libraries
    runs-on: ubuntu-latest
    needs: [build-arm64-v8a, build-armeabi-v7a, build-x86]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: pjsua2-all-architectures
          path: |
            libpjsua2-arm64-v8a/libpjsua2.so
            libpjsua2-armeabi-v7a/libpjsua2.so
            libpjsua2-x86/libpjsua2.so
