name: Build PJSUA2 for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Add NDK to PATH
        run: |
          echo "ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Install SWIG and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake libtool pkg-config
          sudo apt-get install -y libssl-dev libcrypto++-dev
          sudo apt-get install -y gcc-multilib
          echo "C_INCLUDE_PATH=/usr/include:/usr/local/include" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/include:/usr/local/include" >> $GITHUB_ENV

      - name: Set up environment variables
        run: |
          echo "BASE_FOLDER=${{ github.workspace }}" >> $GITHUB_ENV
          CONFIG_SITE_PATH="${{ github.workspace }}/pjlib/include/pj/config_site.h"
          mkdir -p "$(dirname "$CONFIG_SITE_PATH")"
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #define PJMEDIA_HAS_G7221_CODEC 1
          #include <pj/config_site_sample.h>
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSUA_MAX_CALLS 10     
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSIP_SSL_USE_BUILTIN 0  // Użyj systemowego OpenSSL zamiast wbudowanego
          #define PJ_SSL_SOCK_IMP PJ_SSL_SOCK_IMP_OPENSSL  // Wymuś użycie OpenSSL
          #define PJ_SSL_SOCK_IMP_OPENSSL 1
          #define PJSIP_HAS_TLS 1
          #define PJ_HAS_SSL_SOCK 1
          EOF

      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

  build-arm64-v8a:
    name: Build for arm64-v8a
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      - name: Build for arm64-v8a
        run: |
          cd ${{ github.workspace }}
          TARGET_ABI=arm64-v8a ./configure-android --use-ndk-cflags --enable-tls
          make dep && make clean && make
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload arm64-v8a artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-arm64-v8a
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a

  build-armeabi-v7a:
    name: Build for armeabi-v7a
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      - name: Build for armeabi-v7a
        run: |
          cd ${{ github.workspace }}
          TARGET_ABI=armeabi-v7a ./configure-android --use-ndk-cflags --enable-tls
          make dep && make clean && make
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload armeabi-v7a artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-armeabi-v7a
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/armeabi-v7a

  build-x86:
    name: Build for x86
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      - name: Build for x86
        run: |
          cd ${{ github.workspace }}
          TARGET_ABI=x86 ./configure-android --use-ndk-cflags --enable-tls
          make dep && make clean && make
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-x86
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/x86

  build-x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Grant execute permissions to all scripts
        run: chmod -R +x ${{ github.workspace }}

      - name: Build for x86_64
        run: |
          cd ${{ github.workspace }}
          TARGET_ABI=x86_64 ./configure-android --use-ndk-cflags --enable-tls
          make dep && make clean && make
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload x86_64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-x86_64
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/x86_64

  upload-all-artifacts:
    name: Upload all compiled libraries
    runs-on: ubuntu-latest
    needs: [build-arm64-v8a, build-armeabi-v7a, build-x86, build-x86_64]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: pjsua2-all-architectures
          path: libpjsua2-*/ 
