name: Build PJSUA2 for Android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Add NDK to PATH
        run: |
          echo "ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Install SWIG and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake libtool pkg-config

      - name: Download and extract OpenSSL
        run: |
          curl -L https://github.com/openssl/openssl/releases/download/openssl-3.4.0/openssl-3.4.0.tar.gz -o openssl.tar.gz
          tar -xvzf openssl.tar.gz

      - name: Set up environment variables
        run: |
          echo "BASE_FOLDER=${{ github.workspace }}" >> $GITHUB_ENV
          CONFIG_SITE_PATH="${{ github.workspace }}/pjlib/include/pj/config_site.h"
          mkdir -p "$(dirname "$CONFIG_SITE_PATH")"
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #include <pj/config_site_sample.h>

          // **Basic settings**
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 0  
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1      
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1

          // **Security & TLS**
          #define PJSIP_HAS_TLS_TRANSPORT 1
          #define PJSIP_HAS_TLS 1
          #define PJ_HAS_SSL_SOCK 1

          // **Android optimization**
          #define PJ_ANDROID 1
          #define PJ_OS_HAS_CHECK_STACK 0
          #define PJ_THREAD_SET_STACK_SIZE 1
          #define PJ_THREAD_DEFAULT_STACK_SIZE 16384  
          #define PJ_ENABLE_EXTRA_CHECK 0

          // **SIP stack customization**
          #define PJSUA_MAX_CALLS 2
          #define PJSIP_MAX_PKT_LEN 4000 
          #define PJSUA_MAX_ACC 10
          #define PJSUA_MAX_PLAYERS 2
          #define PJSUA_MAX_RECORDERS 2

          // **Additional optimizations**
          #define PJ_IOQUEUE_MAX_HANDLES 64
          #define PJ_LOG_MAX_LEVEL 2 
          #define PJ_POOL_ALIGNMENT 4
          #define PJ_POOL_INCREMENT_SIZE 128
          #define PJ_POOL_ALLOC_POLICY 2
          EOF

      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

  build-arm64:
    name: Build arm64-v8a
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Build OpenSSL for arm64-v8a
        run: |
          cd ${{ github.workspace }}/openssl-3.4.0
          export CC=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang
          ./Configure android-arm64 -D__ANDROID_API__=23
          make -j$(nproc)

      - name: Build PJSUA2 for arm64-v8a
        run: |
          export OPENSSL_DIR=${{ github.workspace }}/openssl-3.4.0
          export CFLAGS="-I$OPENSSL_DIR/include"
          export LDFLAGS="-L$OPENSSL_DIR"
          export CPPFLAGS="-I$OPENSSL_DIR/include"
          export PKG_CONFIG_PATH="$OPENSSL_DIR/pkgconfig"

          cd ${{ github.workspace }}
          ./configure-android --use-ndk-cflags --with-ssl=$OPENSSL_DIR/include
          make dep && make clean && make

      - name: Upload arm64-v8a libraries
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-arm64-v8a
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a

  build-java:
    name: Build Java files
    runs-on: ubuntu-latest
    needs: build-arm64

    steps:
      - name: Download arm64-v8a artifact
        uses: actions/download-artifact@v4
        with:
          name: libpjsua2-arm64-v8a
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a

      - name: Build Java bindings
        run: |
          cd ${{ github.workspace }}/pjsip-apps/src/swig
          make

      - name: Upload Java artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-java
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/

  build-other-architectures:
    name: Build other architectures
    runs-on: ubuntu-latest
    needs: build-java
    strategy:
      matrix:
        architecture: [armeabi-v7a, x86, x86_64]

    steps:
      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: pjsua2-environment-${{ github.run_id }}

      - name: Build OpenSSL for ${{ matrix.architecture }}
        run: |
          cd ${{ github.workspace }}/openssl-3.4.0
          case "${{ matrix.architecture }}" in
            armeabi-v7a)
              export CC=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi23-clang
              ./Configure android-arm -D__ANDROID_API__=23 ;;
            x86)
              export CC=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android23-clang
              ./Configure android-x86 -D__ANDROID_API__=23 ;;
            x86_64)
              export CC=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android23-clang
              ./Configure android-x86_64 -D__ANDROID_API__=23 ;;
          esac
          make -j$(nproc)

      - name: Build PJSUA2 for ${{ matrix.architecture }}
        run: |
          export OPENSSL_DIR=${{ github.workspace }}/openssl-3.4.0
          cd ${{ github.workspace }}
          ./configure-android --use-ndk-cflags --with-ssl=$OPENSSL_DIR/include
          make dep && make clean && make

      - name: Upload architecture-specific libraries
        uses: actions/upload-artifact@v4
        with:
          name: libpjsua2-${{ matrix.architecture }}
          path: ${{ github.workspace }}/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/${{ matrix.architecture }}
