name: Build PJSIP for Android (pjsua2 only)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup-config:
    name: Set up shared config_site.h
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c # Specify the NDK version (latest stable or preferred version)

      - name: Set up environment variables and create config_site.h
        run: |
          BASE_FOLDER=$(pwd)
          PJSIP_BASE_PATH="${BASE_FOLDER}/pjproject"
          CONFIG_SITE_PATH="${PJSIP_BASE_PATH}/pjlib/include/pj/config_site.h"

          # Create a single config_site.h file
          cat <<EOF > "$CONFIG_SITE_PATH"
          #define PJ_CONFIG_ANDROID 1
          #define PJMEDIA_HAS_G7221_CODEC 1
          #include <pj/config_site_sample.h>
          #define PJMEDIA_HAS_VIDEO 0
          #define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
          #define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1
          #define PJSIP_AUTH_AUTO_SEND_NEXT 1
          EOF

  build-arm64-v8a:
    name: Build PJSIP for arm64-v8a
    runs-on: ubuntu-latest
    needs: setup-config

    steps:
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Set up environment variables and build folders for arm64-v8a
        run: |
          BASE_FOLDER=$(pwd)
          PJSIP_BASE_PATH="${BASE_FOLDER}/pjproject"
          PJSIP_TMP_PATH="/tmp/pjsip-arm64-v8a"
          FINAL_BUILD_DIR="${BASE_FOLDER}/pjsip-build-arm64-v8a"
          FINAL_BUILD_LIB="${FINAL_BUILD_DIR}/lib"
          FINAL_BUILD_LOGS="${FINAL_BUILD_DIR}/logs"

          export ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64
          export PATH=$ANDROID_NDK_ROOT:$PATH

          # Clear and set up build directories
          rm -rf "${FINAL_BUILD_DIR}"
          mkdir -p "${FINAL_BUILD_LIB}"
          mkdir -p "${FINAL_BUILD_LOGS}"

      - name: Build PJSIP for arm64-v8a
        run: |
          ARCH="arm64-v8a"
          PJSIP_TMP_PATH="/tmp/pjsip-arm64-v8a"
          mkdir -p "$PJSIP_TMP_PATH"
          cp -r ${PJSIP_BASE_PATH}/* "$PJSIP_TMP_PATH"
          cd "$PJSIP_TMP_PATH"

          APP_PLATFORM=android-21 TARGET_ABI=$ARCH ./configure-android --use-ndk-cflags >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1
          make dep >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1
          make >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1

          # Copy built libraries to final directory
          mkdir -p "${FINAL_BUILD_LIB}/${ARCH}"
          cp pjsip-apps/src/swig/java/android/libs/$ARCH/libpjsua2.so "${FINAL_BUILD_LIB}/${ARCH}/" || true

  build-armeabi-v7a:
    name: Build PJSIP for armeabi-v7a
    runs-on: ubuntu-latest
    needs: setup-config

    steps:
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Set up environment variables and build folders for armeabi-v7a
        run: |
          BASE_FOLDER=$(pwd)
          PJSIP_BASE_PATH="${BASE_FOLDER}/pjproject"
          PJSIP_TMP_PATH="/tmp/pjsip-armeabi-v7a"
          FINAL_BUILD_DIR="${BASE_FOLDER}/pjsip-build-armeabi-v7a"
          FINAL_BUILD_LIB="${FINAL_BUILD_DIR}/lib"
          FINAL_BUILD_LOGS="${FINAL_BUILD_DIR}/logs"

          export ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64
          export PATH=$ANDROID_NDK_ROOT:$PATH

          # Clear and set up build directories
          rm -rf "${FINAL_BUILD_DIR}"
          mkdir -p "${FINAL_BUILD_LIB}"
          mkdir -p "${FINAL_BUILD_LOGS}"

      - name: Build PJSIP for armeabi-v7a
        run: |
          ARCH="armeabi-v7a"
          PJSIP_TMP_PATH="/tmp/pjsip-armeabi-v7a"
          mkdir -p "$PJSIP_TMP_PATH"
          cp -r ${PJSIP_BASE_PATH}/* "$PJSIP_TMP_PATH"
          cd "$PJSIP_TMP_PATH"

          APP_PLATFORM=android-21 TARGET_ABI=$ARCH ./configure-android --use-ndk-cflags >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1
          make dep >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1
          make >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1

          # Copy built libraries to final directory
          mkdir -p "${FINAL_BUILD_LIB}/${ARCH}"
          cp pjsip-apps/src/swig/java/android/libs/$ARCH/libpjsua2.so "${FINAL_BUILD_LIB}/${ARCH}/" || true

  build-x86:
    name: Build PJSIP for x86
    runs-on: ubuntu-latest
    needs: setup-config

    steps:
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Set up environment variables and build folders for x86
        run: |
          BASE_FOLDER=$(pwd)
          PJSIP_BASE_PATH="${BASE_FOLDER}/pjproject"
          PJSIP_TMP_PATH="/tmp/pjsip-x86"
          FINAL_BUILD_DIR="${BASE_FOLDER}/pjsip-build-x86"
          FINAL_BUILD_LIB="${FINAL_BUILD_DIR}/lib"
          FINAL_BUILD_LOGS="${FINAL_BUILD_DIR}/logs"

          export ANDROID_NDK_ROOT=/opt/hostedtoolcache/ndk/r27c/x64
          export PATH=$ANDROID_NDK_ROOT:$PATH

          # Clear and set up build directories
          rm -rf "${FINAL_BUILD_DIR}"
          mkdir -p "${FINAL_BUILD_LIB}"
          mkdir -p "${FINAL_BUILD_LOGS}"

      - name: Build PJSIP for x86
        run: |
          ARCH="x86"
          PJSIP_TMP_PATH="/tmp/pjsip-x86"
          mkdir -p "$PJSIP_TMP_PATH"
          cp -r ${PJSIP_BASE_PATH}/* "$PJSIP_TMP_PATH"
          cd "$PJSIP_TMP_PATH"

          APP_PLATFORM=android-21 TARGET_ABI=$ARCH ./configure-android --use-ndk-cflags >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1
          make dep >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1
          make >>"${FINAL_BUILD_LOGS}/${ARCH}.log" 2>&1

          # Copy built libraries to final directory
          mkdir -p "${FINAL_BUILD_LIB}/${ARCH}"
          cp pjsip-apps/src/swig/java/android/libs/$ARCH/libpjsua2.so "${FINAL_BUILD_LIB}/${ARCH}/" || true

  # Optional: Add a step to upload the artifacts (the .so files)
  upload-artifacts:
    name: Upload artifacts
    runs-on: ubuntu-latest
    needs: [build-arm64-v8a, build-armeabi-v7a, build-x86]
    steps:
      - name: Upload libraries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pjsip-libs
          path: pjsip-build*
