name: CI Ubuntu
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]
env:
  CI_ARGS: ${{ vars.CI_UBUNTU_ARGS }}
  CI_MODE: ${{ vars.CI_MODE }}
  MAKE_FAST: make -j 3
jobs:
  default-build:
    # checking pure lib source distribution with plain configure & make
    runs-on: ubuntu-latest
    name: Default / build only
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: $MAKE_FAST
    - name: get SSL info
      run: pjlib/bin/pjlib-test-`make infotarget` --config --list | grep SSL
    - name: verify oepnssl is used
      run: pjlib/bin/pjlib-test-`make infotarget` --config --list | grep -E 'PJ_SSL_SOCK_IMP\s+:\s+1'

  default-full-bundle-3:
    runs-on: ubuntu-latest
    name: Default / pjsip
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libopencore-amrnb-dev
    - name: config site
      run: cd pjlib/include/pj && cp config_site_test.h config_site.h
    - name: configure
      run: CFLAGS="-g" LDFLAGS="-rdynamic" ./configure
    - name: make
      run: $MAKE_FAST
    - name: pjsip-test
      run: make pjsip-test
